services:
  evolution-api:
    image: ghcr.io/rauankz/evolution-api:latest
    container_name: evolution-api
    ports:
      - "3000:3000"
    depends_on:
      - evolution-postgres
    restart: always
    environment:
      - DATABASE_URL=postgresql://evolution_user:evolution_pass@evolution-postgres:5432/evolutiondb
    volumes:
      - evolution_data:/app

  evolution-postgres:
    image: postgres:16
    container_name: evolution-postgres
    restart: always
    environment:
      POSTGRES_USER: evolution_user
      POSTGRES_PASSWORD: evolution_pass
      POSTGRES_DB: evolutiondb
    volumes:
      - evolution_postgres_data:/var/lib/postgresql/data

volumes:
  evolution_postgres_data:
  evolution_data:
